import type { Metadata } from "next";
import { bodyFont, accentFont } from "@/app/fonts";

import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(bodyFont.variable, accentFont.variable)}>
      <body className="font-sans antialiased">{children}</body>
    </html>
  );
}
